CREATE DATABASE database_frontify;
USE database_frontify;

CREATE TABLE color(id INT AUTO_INCREMENT NOT NULL,name VARCHAR(255) NOT NULL UNIQUE, hexCode VARCHAR(255) NOT NULL,createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE 'utf8mb4_unicode_ci' ENGINE = InnoDB;
